### ISSUE TITLE
Errors on image from docker hub

### ISSUE THREAD

**Issue by HasseM** [kenwaytis/faster-SadTalker-API#12]
When I just take the image from docker hub, it should work without any additional steps, right?

This is what I get:

`2024-01-03 19:06:44 

2024-01-03 19:06:44 ==========

2024-01-03 19:06:44 == CUDA ==

2024-01-03 19:06:44 ==========

2024-01-03 19:06:44 
2024-01-03 19:06:44 CUDA Version 11.8.0
2024-01-03 19:06:44 
2024-01-03 19:06:44 Container image Copyright (c) 2016-2023, NVIDIA CORPORATION & AFFILIATES. All rights reserved.
2024-01-03 19:06:44 
2024-01-03 19:06:44 This container image and its contents are governed by the NVIDIA Deep Learning Container License.
2024-01-03 19:06:44 By pulling and using the container, you accept the terms and conditions of this license:
2024-01-03 19:06:44 https://developer.nvidia.com/ngc/nvidia-deep-learning-container-license
2024-01-03 19:06:44 
2024-01-03 19:06:44 A copy of this license is made available in this container at /NGC-DL-CONTAINER-LICENSE for your convenience.
2024-01-03 19:06:44 
2024-01-03 19:06:44 WARNING: The NVIDIA Driver was not detected.  GPU functionality will not be available.
2024-01-03 19:06:44    Use the NVIDIA Container Toolkit to start this container with GPU support; see
2024-01-03 19:06:44    https://docs.nvidia.com/datacenter/cloud-native/ .
2024-01-03 19:06:44 
2024-01-03 19:06:50 font_manager.py     :1547 2024-01-03 18:06:50,240 generated new fontManager
2024-01-03 19:06:50 Traceback (most recent call last):
2024-01-03 19:06:50   File "/handler.py", line 8, in <module>
2024-01-03 19:06:50     from inference import main
2024-01-03 19:06:50   File "/inference.py", line 9, in <module>
2024-01-03 19:06:50     from src.facerender.animate import AnimateFromCoeff
2024-01-03 19:06:50   File "/src/facerender/animate.py", line 27, in <module>
2024-01-03 19:06:50     from utils import upload_firebase_file, save_video_without_watermark
2024-01-03 19:06:50   File "/utils.py", line 31, in <module>
2024-01-03 19:06:50     load_credentials()        
2024-01-03 19:06:50   File "/utils.py", line 17, in load_credentials
2024-01-03 19:06:50     "project_id": os.environ["project_id"],
2024-01-03 19:06:50   File "/usr/lib/python3.8/os.py", line 675, in __getitem__
2024-01-03 19:06:50     raise KeyError(key) from None
2024-01-03 19:06:50 KeyError: 'project_id'`

I have an RTX3090 and all NVideo drivers installed but I am on Win11. I'm really looking for a way to get ST working through an API or commandline. I have it running as a SD extension but no way to externally control it that way. So I was looking for running solutions in Docker with an API. Found yours. But these ST docker images seem to have problems with nvidia?

**Comment by eoffermann** [comment]
Looks like you haven't installed the NVidia Container Toolkit - https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/latest/install-guide.html
